apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  namespace: nextcloud
  name: nextcloud-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <ENV-YOUR-EMAIL-GOES-HERE>
    privateKeySecretRef:
       name: nextcloud-letsencrypt
    solvers:
    - http01:
        ingress:
          class: public
