apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "database-data"
  namespace: nextcloud
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: <ENV-STORAGE-AMOUNT>