apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nextcloud-data"
  namespace: nextcloud
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "250Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/sda1/nextcloud/data"