apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "nextcloud-data"
  namespace: nextcloud
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "250Gi"